CREATE TABLE IF NOT EXISTS players (
  id SERIAL PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  handle TEXT NOT NULL DEFAULT '',
  sex INTEGER NOT NULL DEFAULT 0,
  class INTEGER NOT NULL DEFAULT 1,
  hit_points INTEGER NOT NULL DEFAULT 15,
  hit_max INTEGER NOT NULL DEFAULT 15,
  strength INTEGER NOT NULL DEFAULT 15,
  defense INTEGER NOT NULL DEFAULT 0,
  charm INTEGER NOT NULL DEFAULT 10,
  level INTEGER NOT NULL DEFAULT 1,
  exp BIGINT NOT NULL DEFAULT 0,
  gold BIGINT NOT NULL DEFAULT 0,
  bank BIGINT NOT NULL DEFAULT 0,
  gems INTEGER NOT NULL DEFAULT 0,
  weapon_num INTEGER NOT NULL DEFAULT 0,
  weapon_name TEXT NOT NULL DEFAULT 'Fists',
  arm_num INTEGER NOT NULL DEFAULT 0,
  arm_name TEXT NOT NULL DEFAULT 'None',
  fights_left INTEGER NOT NULL DEFAULT 10,
  human_fights_left INTEGER NOT NULL DEFAULT 5,
  skill_points INTEGER NOT NULL DEFAULT 0,
  skill_uses_left INTEGER NOT NULL DEFAULT 0,
  dead INTEGER NOT NULL DEFAULT 0,
  seen_master INTEGER NOT NULL DEFAULT 0,
  seen_dragon INTEGER NOT NULL DEFAULT 0,
  has_horse INTEGER NOT NULL DEFAULT 0,
  married_to INTEGER NOT NULL DEFAULT -1,
  kids INTEGER NOT NULL DEFAULT 0,
  times_won INTEGER NOT NULL DEFAULT 0,
  kills INTEGER NOT NULL DEFAULT 0,
  lays INTEGER NOT NULL DEFAULT 0,
  last_day INTEGER NOT NULL DEFAULT 0,
  flirted_today INTEGER NOT NULL DEFAULT 0,
  special_done_today INTEGER NOT NULL DEFAULT 0,
  setup_complete INTEGER NOT NULL DEFAULT 0,
  last_seen TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS news (
  id SERIAL PRIMARY KEY,
  day INTEGER NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS hall_of_kings (
  id SERIAL PRIMARY KEY,
  handle TEXT NOT NULL,
  level INTEGER NOT NULL DEFAULT 12,
  kills INTEGER NOT NULL DEFAULT 0,
  class INTEGER NOT NULL DEFAULT 1,
  times_won INTEGER NOT NULL DEFAULT 1,
  defeated_at TIMESTAMP NOT NULL DEFAULT NOW()
);
