CREATE TABLE IF NOT EXISTS player_mail (
  id SERIAL PRIMARY KEY,
  from_id INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  to_id INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  message TEXT NOT NULL,
  read INTEGER NOT NULL DEFAULT 0,
  sent_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_player_mail_to_id ON player_mail(to_id);
