ALTER TABLE players
  ADD COLUMN IF NOT EXISTS wounds          TEXT    NOT NULL DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS infection_type  TEXT    NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS infection_stage INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS infection_days  INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS vampire_bites   INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS is_vampire      INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS vampire_feasted INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS retired_today   INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS retired_town    TEXT    NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS bandages        INTEGER NOT NULL DEFAULT 0;
