-- Named & cursed item slots on the player record
ALTER TABLE players ADD COLUMN IF NOT EXISTS named_weapon_id TEXT DEFAULT NULL;
ALTER TABLE players ADD COLUMN IF NOT EXISTS named_armor_id  TEXT DEFAULT NULL;
ALTER TABLE players ADD COLUMN IF NOT EXISTS weapon_cursed   BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE players ADD COLUMN IF NOT EXISTS armor_cursed    BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE players ADD COLUMN IF NOT EXISTS blood_oath      BOOLEAN NOT NULL DEFAULT FALSE;
